import { Inter } from "next/font/google";
import { ThemeModeScript } from "flowbite-react";
import SessionProvider from "@/components/SessionProvider"
import { getServerSession } from 'next-auth'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Baloo+Tammudu+2:wght@400..800&family=Koh+Santepheap:wght@100;300;400;700;900&display=swap" rel="stylesheet" />
        <title>
          CaReMap
        </title>
      </head>
      <body className={inter.className}>
      <SessionProvider session={session}> 
        {children}
        </SessionProvider>
        </body>
    </html>
  );
}
